name       : gramps
version    : 4.2.5
release    : 4
source     :
    - https://github.com/gramps-project/gramps/archive/v4.2.5.tar.gz : 1de3007215b7d0b779ec8f086e14e7a75f2aa811ee37c6d0cff06bfc9458743d
license    : GPL-2.0
component  : desktop
summary    : Gramps genealogical research software
description: |
    Gramps genealogical research software
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(python-3.5)
rundeps    :
    - graphviz
    - osm-gps-map
    - pyexiv2
    - pyicu
    - python3-bsddb3
    - python3-gobject
    - python-pillow
    - pyxdg
build      : |
    %python3_setup
install    : |-
    %python3_install --no-compile
    sed -i "s|$installdir||" $installdir/usr/lib/python3.5/site-packages/gramps/gen/utils/resource-path
