name       : gramps
version    : 4.2.3
release    : 2
source     :
    - https://github.com/gramps-project/gramps/archive/v4.2.3.tar.gz : a7c998a8303a84bd05a6067b5aba230cf6037a29dcdb3e7ca6c06969da4590a5
license    : GPL-2.0
component  : desktop
summary    : Gramps genealogical research software
description: |
    Gramps genealogical research software
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(python-3.5)
rundeps    :
    - graphviz
    - pyicu
    - python3-bsddb3
    - python3-gobject
    - python-pillow
    - pyxdg
build      : |
    %python3_setup
install    : |-
    %python3_install --no-compile
    sed -i "s|$installdir||" $installdir/usr/lib/python3.5/site-packages/gramps/gen/utils/resource-path
