name       : gramps
version    : 5.0.1
release    : 11
source     :
    - https://github.com/gramps-project/gramps/archive/v5.0.1.tar.gz : 3a81265764a314cca0540593ccd639c5b76199615b3b0aace0b2540fc186eba5
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Gramps genealogical research software
description: |
    Gramps genealogical research software
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(python3)
rundeps    :
    - goocanvas
    - graphviz
    - osm-gps-map
    - pyexiv2
    - pygoocanvas
    - pyicu
    - python3-bsddb3
    - python3-gobject
    - python-pillow
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install
    sed -i "s|$installdir||" $installdir/usr/lib/python%python3_version%/site-packages/gramps/gen/utils/resource-path
