name       : gramps
version    : 4.2.6
release    : 6
source     :
    - https://github.com/gramps-project/gramps/archive/v4.2.6.tar.gz : 6f6f2afe745179e2e66f216f25ca2ba4bf4d5f6bd3b553bbb2946df0636a0bed
license    : GPL-2.0
component  : office.scientific
summary    : Gramps genealogical research software
description: |
    Gramps genealogical research software
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(python-3.5)
rundeps    :
    - graphviz
    - osm-gps-map
    - pyexiv2
    - pyicu
    - python3-bsddb3
    - python3-gobject
    - python-pillow
    - pyxdg
build      : |
    %python3_setup
install    : |-
    %python3_install --no-compile
    sed -i "s|$installdir||" $installdir/usr/lib/python3.5/site-packages/gramps/gen/utils/resource-path
