name       : gramps
version    : 5.1.6
release    : 21
source     :
    - https://github.com/gramps-project/gramps/archive/v5.1.6.tar.gz : bff0b5694e77e0f7075fb76481c4523d37646cc042c8dd9897ff2e0cd401fa3b
homepage   : https://gramps-project.org
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Gramps genealogical research software
description: |
    Gramps is a free software project and community. We strive to produce a genealogy program that is both intuitive for hobbyists and feature-complete for professional genealogists. It is a community project, created, developed and governed by genealogists.
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(python3)
rundeps    :
    - gexiv2
    - goocanvas
    - graphviz
    - osm-gps-map
    - pyicu
    - python-gobject
    - python-pillow
    - python3-bsddb3
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install
    sed -i "s|$installdir||" $installdir/usr/lib/python%python3_version%/site-packages/gramps/gen/utils/resource-path
