name       : gramps
version    : 5.1.3
release    : 17
source     :
    - https://github.com/gramps-project/gramps/archive/v5.1.3.tar.gz : 91d755b7e407af40ce5ebe24b29baab860bc6e2871ebcbee3f5e109c438df1e8
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Gramps genealogical research software
description: |
    Gramps genealogical research software
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(python3)
rundeps    :
    - gexiv2
    - goocanvas
    - graphviz
    - osm-gps-map
    - pyicu
    - python3-bsddb3
    - python-gobject
    - python-pillow
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install
    sed -i "s|$installdir||" $installdir/usr/lib/python%python3_version%/site-packages/gramps/gen/utils/resource-path
