name       : gramps
version    : 4.2.8
release    : 9
source     :
    - https://github.com/gramps-project/gramps/archive/v4.2.8.tar.gz : aa2c18cdeb3d7fc07f0013d5ca9c651f3bd4aa02f03010966857f804b227668d
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Gramps genealogical research software
description: |
    Gramps genealogical research software
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(python3)
rundeps    :
    - goocanvas
    - graphviz
    - osm-gps-map
    - pyexiv2
    - pygoocanvas
    - pyicu
    - python3-bsddb3
    - python3-gobject
    - python-pillow
    - pyxdg
build      : |
    %python3_setup
install    : |-
    %python3_install --no-compile
    sed -i "s|$installdir||" $installdir/usr/lib/python3.6/site-packages/gramps/gen/utils/resource-path
