name       : gramps
version    : 5.1.0
release    : 12
source     :
    - https://github.com/gramps-project/gramps/archive/v5.1.0.tar.gz : 9e09ab9f196e66858b62a35f5387b4b0a9ce13c0cb0bf4fd78257be77b45abf3
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Gramps genealogical research software
description: |
    Gramps genealogical research software
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(python3)
rundeps    :
    - goocanvas
    - graphviz
    - osm-gps-map
    - pygoocanvas
    - pyicu
    - python3-bsddb3
    - python3-gobject
    - python-pillow
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install
    sed -i "s|$installdir||" $installdir/usr/lib/python%python3_version%/site-packages/gramps/gen/utils/resource-path
