name       : gramps
version    : 5.1.2
release    : 15
source     :
    - https://github.com/gramps-project/gramps/archive/v5.1.2.tar.gz : 4f11d7fa66e397a36c902057794c48c0740d56c802fcdc5f2c3e3652104dd45b
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Gramps genealogical research software
description: |
    Gramps genealogical research software
builddeps  :
    - pkgconfig(gexiv2)
    - pkgconfig(gtkspell3-3.0)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(pangocairo)
    - pkgconfig(python3)
rundeps    :
    - goocanvas
    - graphviz
    - osm-gps-map
    - pygoocanvas
    - pyicu
    - python3-bsddb3
    - python-gobject
    - python-pillow
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install
    sed -i "s|$installdir||" $installdir/usr/lib/python%python3_version%/site-packages/gramps/gen/utils/resource-path
